run:
  timeout: 5m
  output:
    format: tab
  skip-dirs:
    - vendor

linters-settings:
  govet:
    check-shadowing: true
  golint:
    min-confidence: 0.1
  maligned:
    suggest-new: true
  goconst:
    min-len: 2
    min-occurrences: 2
  misspell:
    locale: US
  lll:
    line-length: 140
  gocritic:
    enabled-tags:
      - performance
      - style
      - experimental
    disabled-checks:
      - wrapperFunc
      - hugeParam
      - rangeValCopy
      - singleCaseSwitch
      - ifElseChain

linters:
  enable:
    - revive
    - govet
    - unconvert
    - gosec
    - dupl
    - misspell
    - unused
    - typecheck
    - ineffassign
    - stylecheck
    - gochecknoinits
    - gocritic
    - nakedret
    - gosimple
    - prealloc
    - copyloopvar
  fast: false
  disable-all: true

issues:
  exclude-rules:
    - text: "package-comments: should have a package comment"
      linters:
        - revive
    - text: "at least one file in a package should have a package comment"
      linters:
        - stylecheck
    - text: "should have a package comment, unless it's in another file for this package"
      linters:
        - golint
    - text: "integer overflow conversion"
      linters:
        - gosec
    - path: _test\.go
      linters:
        - gosec
        - dupl
    - linters:
        - unparam
        - unused
        - revive
      path: _test\.go$
      text: "unused-parameter"
  exclude-use-default: false
