signs:
  - artifacts: checksum

project_name: spot

builds:
  - id: spot
    binary: "spot"
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm
      - arm64
    ignore:
      - goos: freebsd
        goarch: arm
      - goos: freebsd
        goarch: arm64
      - goos: windows
        goarch: arm
      - goos: windows
        goarch: arm64
    dir: cmd/spot
    ldflags: "-s -w -X main.revision={{.Tag}}-{{.ShortCommit}}-{{.CommitDate}}"

  - id: secrets
    binary: "spot-secrets"
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm
      - arm64
    ignore:
      - goos: freebsd
        goarch: arm
      - goos: freebsd
        goarch: arm64
      - goos: windows
        goarch: arm
      - goos: windows
        goarch: arm64
    dir: cmd/secrets
    ldflags: "-s -w -X main.revision={{.Tag}}-{{.ShortCommit}}-{{.CommitDate}}"

archives:
  - name_template: "{{.ProjectName}}_{{.Tag}}_{{.Os}}_{{.Arch}}"
    replacements:
      386: i386
      amd64: x86_64
      darwin: macos
    format_overrides:
      - goos: windows
        format: zip
    files:
      - LICENSE
      - README.md
      - "dist/{{ .ProjectName }}_{{ .Tag }}_{{ .Os }}_{{ .Arch }}/spot*"
      - "dist/{{ .ProjectName }}_{{ .Tag }}_{{ .Os }}_{{ .Arch }}/spot-secrets*"

brews:
  -
    name: spot
    tap:
      owner: umputun
      name: homebrew-apps
      branch: main
    commit_author:
      name: umputun
      email: umputun@gmail.com
    commit_msg_template: "Brew formula update for {{ .ProjectName }} version {{ .Tag }}"
    homepage: "https://simplotask.com/"
    description: "Spot (aka simplotask) is a powerful and easy-to-use tool for effortless deployment and configuration management."
    license: "MIT"

nfpms:
  - id: spot
    package_name: spot
    file_name_template: "{{.ProjectName}}_{{.Tag}}_{{.Os}}_{{.Arch}}"
    vendor: Umputun
    homepage: https://simplotask.com
    maintainer: Umputun <umputun@gmail.com>
    description: A collection of tools for the effortless deployment, configuration, and management of secrets
    license: MIT
    formats:
      - deb
      - rpm
    bindir: /usr/bin
    epoch: 1
    release: 1


